apiVersion: v1
kind: Service
metadata:
  name: slurm-container
  namespace: argo
spec:
  selector:
    app: slurm-container
  ports:
    - name: ssh
      port: 22
      targetPort: 22
  type: ClusterIP
