apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurm-container
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurm-container
  template:
    metadata:
      labels:
        app: slurm-container
    spec:
      hostname: slurmctl
      containers:
        - name: slurm
          image: ghcr.io/pgpalt/slurm-container:main
          command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
          ports:
            - containerPort: 22
              name: ssh
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: ssh-authorized-key
              mountPath: /root/.ssh
              readOnly: true
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu:  "1"
              memory: "1536Mi"
      volumes:
        - name: ssh-authorized-key
          secret:
            secretName: slurm-authorized-key
            defaultMode: 0600
            items:
              - key: authorized_keys
                path: authorized_keys
