apiVersion: hybridwf.io/v1alpha1
kind: HybridWorkflow
metadata:
  labels:
    app.kubernetes.io/name: hybrid-workflows-operator
    app.kubernetes.io/managed-by: kustomize
  name: variations
  namespace: argo
spec:  
  jobs:
    - name: gen-epochs
      type: k8s
      jobSpec:
        script:
          image: python:alpine3.6
          command:
            - python
          source: |
            import random
            print(60000//random.randint(40000, 40000))

    - name: generate
      type: k8s
      jobSpec:
        container:
          image: busybox
          command: [sh, -c]
          args: ["echo hello world 1 | tee /tmp/file1.txt && echo hello world 2 | tee /tmp/file2.txt"]
        outputs:
          parameters:
            - name: output-param-1
              valueFrom:
                path: /tmp/file1.txt
          artifacts:
            - name: file1
              path: /tmp/file1.txt
              s3:
                key: Mnist-Dataset/my-file1
              archive:
                none: { }  
            - name: file2
              path: /tmp/file2.txt
              s3:
                key: Mnist-Dataset/my-file2
              archive:
                none: { }                

    - name: print-message-from-slurm-output
      type: k8s
      jobSpec:
        inputs:
          artifacts:
          # unpack the message input artifact
          # and put it at /tmp/message
          - name: message
            path: /tmp/message
        container:
          image: alpine:latest
          command: [sh, -c]
          args: ["cat /tmp/message/mnist.log"] 
      inputs:
        - name: message
          from: model-training1
          type: artifact      

    - name: print-slurm-message-from-slurm-output
      type: slurm
      command: "cat mnist.log"
      inputs:
        - from: model-training1

    - name: print-message-from-files
      type: k8s
      jobSpec:
        inputs:
          artifacts:
          - name: message1
            path: /tmp/message1
          - name: message2
            path: /tmp/message2
        container:
          image: alpine:latest
          command: [sh, -c]
          args: ["cat /tmp/message1 && cat /tmp/message2"] 
      inputs:
        - name: message1
          from: generate.file1   
          type: artifact 
        - name: message2
          from: generate.file2   
          type: artifact             

    - name: print-message-from-parameter
      type: k8s
      jobSpec:
        inputs:
          parameters:
            - name: template-param-1
        script:
          image: alpine
          command: [/bin/sh]
          source: |
              echo "{{inputs.parameters.template-param-1}}"
      inputs:
        - name: template-param-1
          from: generate.output-param-1
          type: parameter

    - name: model-training1
      type: slurm
      command: "export LR=0.017 && export epochs={{tasks.gen-epochs.outputs.result}} && sbatch katib-train-local.slurm"
      inputs:
        - s3key: Mnist-Dataset
          path: /tmp/mnist-job/
        - from: gen-epochs
      outputs:
        - name: outputFileName
          value: mnist.log

    - name: model-training2
      type: slurm
      command: "export LR=0.017 && cat my-file1 && cat my-file2 && export epochs={{tasks.gen-epochs.outputs.result}} && cat /tmp/mnist-job/mnist.log && sbatch katib-train-local.slurm"
      inputs:
        - s3key: Mnist-Dataset
        - from: gen-epochs
        - from: generate
        - from: model-training1
      outputs:
        - name: outputFileName
          value: mnist.log