apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: argo
  name: katib-argo-workflow
spec:
  objective:
    type: minimize
    goal: 0.05
    objectiveMetricName: loss
  metricsCollectorSpec:
    source:
      filter:
        metricsFormat:
          - "{metricName: ([\\w|-]+), metricValue: ((-?\\d+)(\\.\\d+)?)}"
      fileSystemPath:
        path: "/katib/mnist.log"
        kind: File
    collector:
      kind: File
  algorithm:
    algorithmName: random
  parallelTrialCount: 2
  maxTrialCount: 5
  maxFailedTrialCount: 1
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
  trialTemplate:
    retain: true
    primaryPodLabels:
      katib.kubeflow.org/model-training: "true"
    primaryContainerName: main
    successCondition: status.[@this].#(phase=="Succeeded")#
    failureCondition: status.[@this].#(phase=="Failed")#
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
    trialSpec:
      apiVersion: hybridwf.io/v1alpha1
      kind: HybridWorkflow
      metadata:
        labels:
          app.kubernetes.io/name: hybrid-workflows-operator
          app.kubernetes.io/managed-by: kustomize
        name: genomic-qc-alignment
        namespace: argo
      spec:
        jobs:
          - name: gen-epochs
            type: k8s
            jobSpec:
              script:
                image: python:alpine3.6
                command:
                  - python
                source: |
                  import random
                  print(60000//random.randint(40000, 40000))

          - name: model-training
            type: slurm
            command: "export LR=${trialParameters.learningRate} && export epochs={{tasks.gen-epochs.outputs.result}} && sbatch katib-train-local.slurm"
            inputs:
              - s3key: Mnist-Dataset
              - from: gen-epochs
            outputs:
              - name: outputFileName
                value: mnist.log

          - name: print-message-from-slurm-output
            type: k8s
            jobSpec:
              inputs:
                artifacts:
                - name: logs
                  path: "/tmp/logs"
              metadata:
                labels:
                  katib.kubeflow.org/model-training: "true"
              container:
                image: busybox:latest
                command: [sh, -c]
                args: ["mkdir -p /katib;cp /tmp/logs/mnist.log /katib/mnist.log;sleep 10;cat /katib/mnist.log;sleep 20"]
            inputs:
              - name: logs
                from: model-training         