//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HybridWorkflow) DeepCopyInto(out *HybridWorkflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HybridWorkflow.
func (in *HybridWorkflow) DeepCopy() *HybridWorkflow {
	if in == nil {
		return nil
	}
	out := new(HybridWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HybridWorkflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HybridWorkflowCondition) DeepCopyInto(out *HybridWorkflowCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HybridWorkflowCondition.
func (in *HybridWorkflowCondition) DeepCopy() *HybridWorkflowCondition {
	if in == nil {
		return nil
	}
	out := new(HybridWorkflowCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HybridWorkflowInput) DeepCopyInto(out *HybridWorkflowInput) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HybridWorkflowInput.
func (in *HybridWorkflowInput) DeepCopy() *HybridWorkflowInput {
	if in == nil {
		return nil
	}
	out := new(HybridWorkflowInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HybridWorkflowJob) DeepCopyInto(out *HybridWorkflowJob) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]HybridWorkflowInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.JobSpec != nil {
		in, out := &in.JobSpec, &out.JobSpec
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]HybridWorkflowOutput, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HybridWorkflowJob.
func (in *HybridWorkflowJob) DeepCopy() *HybridWorkflowJob {
	if in == nil {
		return nil
	}
	out := new(HybridWorkflowJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HybridWorkflowList) DeepCopyInto(out *HybridWorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HybridWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HybridWorkflowList.
func (in *HybridWorkflowList) DeepCopy() *HybridWorkflowList {
	if in == nil {
		return nil
	}
	out := new(HybridWorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HybridWorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HybridWorkflowOutput) DeepCopyInto(out *HybridWorkflowOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HybridWorkflowOutput.
func (in *HybridWorkflowOutput) DeepCopy() *HybridWorkflowOutput {
	if in == nil {
		return nil
	}
	out := new(HybridWorkflowOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HybridWorkflowSpec) DeepCopyInto(out *HybridWorkflowSpec) {
	*out = *in
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]HybridWorkflowJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HybridWorkflowSpec.
func (in *HybridWorkflowSpec) DeepCopy() *HybridWorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(HybridWorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HybridWorkflowStatus) DeepCopyInto(out *HybridWorkflowStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]HybridWorkflowCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HybridWorkflowStatus.
func (in *HybridWorkflowStatus) DeepCopy() *HybridWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(HybridWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}
