#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
gitops_dir="$(cd "${repo_root}/.." && pwd)/hybrid-workflows-gitops"

argocd_nodeport="${ARGOCD_NODEPORT:-32002}"
argocd_password="${ARGOCD_PASSWORD:-}"
argocd_version="${ARGOCD_VERSION:-v3.1.1}"
slurm_container_name="${SLURM_CONTAINER_NAME:-slurm-container}"
relay_log="${RELAY_LOG:-${TMPDIR:-/tmp}/hybrid-workflows-nodeport-relay.log}"
start_nodeport_relays="${START_NODEPORT_RELAYS:-auto}"
minio_bucket="${MINIO_BUCKET:-my-bucket}"
minio_access_key="${MINIO_ACCESS_KEY:-}"
minio_secret_key="${MINIO_SECRET_KEY:-}"
minio_client_image="${MINIO_CLIENT_IMAGE:-minio/mc}"
credentials_dir="${HOME}/.config/hybrid-workflows-operator"
credentials_file="${SETUP_CREDENTIALS_FILE:-${credentials_dir}/dev-credentials.env}"
ssh_dir="${HOME}/.ssh/slurm"
ssh_key_path="${ssh_dir}/id_ed25519"

require_command() {
  local command_name="$1"
  if ! command -v "${command_name}" >/dev/null 2>&1; then
    echo "${command_name} is required but not installed or not on PATH." >&2
    exit 1
  fi
}

is_container_runtime() {
  [ -f "/.dockerenv" ] || [ -n "${CODESPACES:-}" ] || [ -n "${REMOTE_CONTAINERS:-}" ]
}

generate_hex() {
  local bytes="$1"
  od -An -N "${bytes}" -tx1 /dev/urandom | tr -d ' \n'
}

load_or_generate_credentials() {
  local stored_argocd_password=""
  local stored_minio_access_key=""
  local stored_minio_secret_key=""
  local credentials_parent_dir=""

  credentials_parent_dir="$(dirname "${credentials_file}")"
  mkdir -p "${credentials_parent_dir}"
  chmod 700 "${credentials_parent_dir}"

  if [ -f "${credentials_file}" ]; then
    # shellcheck disable=SC1090
    . "${credentials_file}"
    stored_argocd_password="${SETUP_ARGOCD_PASSWORD:-}"
    stored_minio_access_key="${SETUP_MINIO_ACCESS_KEY:-}"
    stored_minio_secret_key="${SETUP_MINIO_SECRET_KEY:-}"
  fi

  argocd_password="${argocd_password:-${stored_argocd_password}}"
  minio_access_key="${minio_access_key:-${stored_minio_access_key}}"
  minio_secret_key="${minio_secret_key:-${stored_minio_secret_key}}"

  if [[ -z "${argocd_password}" ]]; then
    argocd_password="argocd-$(generate_hex 12)"
  fi
  if [[ -z "${minio_access_key}" ]]; then
    minio_access_key="minio$(generate_hex 4)"
  fi
  if [[ -z "${minio_secret_key}" ]]; then
    minio_secret_key="$(generate_hex 16)"
  fi

  {
    echo "# Generated by scripts/setup.sh"
    printf 'SETUP_ARGOCD_PASSWORD=%q\n' "${argocd_password}"
    printf 'SETUP_MINIO_ACCESS_KEY=%q\n' "${minio_access_key}"
    printf 'SETUP_MINIO_SECRET_KEY=%q\n' "${minio_secret_key}"
  } > "${credentials_file}"
  chmod 600 "${credentials_file}"
}

install_argocd_if_missing() {
  local machine arch download_url install_dir

  install_dir="${HOME}/.local/bin"
  export PATH="${install_dir}:${PATH}"

  if command -v argocd >/dev/null 2>&1; then
    return
  fi

  machine="$(uname -m)"
  case "${machine}" in
    x86_64)
      arch="amd64"
      ;;
    aarch64|arm64)
      arch="arm64"
      ;;
    *)
      echo "Unsupported architecture ${machine} for argocd install." >&2
      exit 1
      ;;
  esac

  download_url="https://github.com/argoproj/argo-cd/releases/download/${argocd_version}/argocd-linux-${arch}"
  mkdir -p "${install_dir}"
  curl -fsSL "${download_url}" -o "${install_dir}/argocd"
  chmod 0755 "${install_dir}/argocd"
}

bcrypt_password() {
  local password="$1"
  argocd account bcrypt --password "${password}"
}

wait_for_service() {
  local namespace="$1"
  local service="$2"
  local timeout_seconds="${3:-600}"
  local deadline=$((SECONDS + timeout_seconds))

  until kubectl get svc "${service}" -n "${namespace}" >/dev/null 2>&1; do
    if (( SECONDS >= deadline )); then
      echo "Timed out waiting for service ${namespace}/${service}." >&2
      exit 1
    fi
    sleep 5
  done
}

get_nodeport() {
  local namespace="$1"
  local service="$2"
  local port="$3"
  local nodeport

  nodeport="$(kubectl get svc "${service}" -n "${namespace}" -o jsonpath="{.spec.ports[?(@.port==${port})].nodePort}")"
  if [[ -z "${nodeport}" ]]; then
    echo "Failed to resolve NodePort for ${namespace}/${service} port ${port}." >&2
    exit 1
  fi
  echo "${nodeport}"
}

run_minio_client() {
  local minio_host="$1"
  local minio_port="$2"
  shift 2

  docker run --rm --network host \
    -v "${repo_root}/examples/Datasets:/datasets:ro" \
    -e "MC_HOST_local=http://${minio_access_key}:${minio_secret_key}@${minio_host}:${minio_port}" \
    "${minio_client_image}" "$@"
}

upload_example_datasets() {
  local minio_host="$1"
  local minio_port="$2"
  local ready="false"

  for _ in $(seq 1 60); do
    if run_minio_client "${minio_host}" "${minio_port}" ls "local/${minio_bucket}" >/dev/null 2>&1; then
      ready="true"
      break
    fi
    sleep 5
  done

  if [[ "${ready}" != "true" ]]; then
    echo "Timed out waiting for MinIO bucket ${minio_bucket} to become reachable." >&2
    exit 1
  fi

  run_minio_client "${minio_host}" "${minio_port}" mb --ignore-existing "local/${minio_bucket}" >/dev/null
  run_minio_client "${minio_host}" "${minio_port}" mirror --overwrite /datasets/GenomicData "local/${minio_bucket}/GenomicData" >/dev/null
  run_minio_client "${minio_host}" "${minio_port}" mirror --overwrite /datasets/GenomicDataAris "local/${minio_bucket}/GenomicDataAris" >/dev/null
  run_minio_client "${minio_host}" "${minio_port}" mirror --overwrite /datasets/Mnist-Dataset "local/${minio_bucket}/Mnist-Dataset" >/dev/null
}

create_or_update_minio_credentials_secret() {
  kubectl create namespace argo --dry-run=client -o yaml | kubectl apply -f -

  kubectl -n argo create secret generic my-minio-cred \
    --from-literal=rootUser="${minio_access_key}" \
    --from-literal=rootPassword="${minio_secret_key}" \
    --from-literal=accesskey="${minio_access_key}" \
    --from-literal=secretkey="${minio_secret_key}" \
    --dry-run=client -o yaml | kubectl apply -f -

  # If this secret used to be managed by Argo CD, detach common tracking metadata
  # so it can become runtime-owned without being pruned on the next sync.
  kubectl -n argo annotate secret my-minio-cred \
    argocd.argoproj.io/tracking-id- \
    argocd.argoproj.io/instance- >/dev/null 2>&1 || true
  kubectl -n argo label secret my-minio-cred \
    app.kubernetes.io/instance- >/dev/null 2>&1 || true
}

restart_workload_if_present() {
  local namespace="$1"
  local resource="$2"
  local name="$3"

  if kubectl get "${resource}" "${name}" -n "${namespace}" >/dev/null 2>&1; then
    kubectl rollout restart "${resource}/${name}" -n "${namespace}" >/dev/null
    kubectl rollout status "${resource}/${name}" -n "${namespace}" --timeout=300s >/dev/null
  fi
}

require_running_minikube() {
  local status

  minikube update-context >/dev/null 2>&1 || true
  status="$(minikube status --format='{{.Host}} {{.Kubelet}} {{.APIServer}}' 2>/dev/null || true)"

  if [[ "${status}" != "Running Running Running" ]]; then
    echo "Minikube must already be running before setup." >&2
    echo "Start it first, for example:" >&2
    echo "  minikube start --driver=docker --cpus=4 --memory=4096 --disk-size=10g" >&2
    exit 1
  fi
}

if [[ "${start_nodeport_relays}" == "auto" ]]; then
  if is_container_runtime; then
    start_nodeport_relays="true"
  else
    start_nodeport_relays="false"
  fi
fi

for command_name in curl git minikube kubectl docker ssh-keygen; do
  require_command "${command_name}"
done
if [[ "${start_nodeport_relays}" == "true" ]]; then
  require_command socat
fi

install_argocd_if_missing
load_or_generate_credentials
require_running_minikube

if [ -e "${gitops_dir}" ] && [ ! -d "${gitops_dir}/.git" ]; then
  echo "Path ${gitops_dir} already exists and is not a git repository." >&2
  exit 1
fi

if [ ! -d "${gitops_dir}/.git" ]; then
  git clone https://github.com/PGpalt/hybrid-workflows-gitops.git "${gitops_dir}"
else
  echo "GitOps repo already exists at ${gitops_dir}; skipping clone."
fi

kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

kubectl apply --server-side --force-conflicts -n argocd \
  -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

kubectl -n argocd wait --for=condition=available deployment/argocd-server --timeout=300s

kubectl -n argocd patch svc argocd-server --type='strategic' -p "{
  \"spec\": {
    \"type\": \"NodePort\",
    \"ports\": [
      {
        \"port\": 443,
        \"nodePort\": ${argocd_nodeport}
      }
    ]
  }
}"

ARGOCD_HASH="$(bcrypt_password "${argocd_password}")"

kubectl -n argocd patch secret argocd-secret -p "{
  \"stringData\": {
    \"admin.password\": \"${ARGOCD_HASH}\",
    \"admin.passwordMtime\": \"$(date -u +%FT%TZ)\"
  }
}"

kubectl -n argocd rollout restart deployment argocd-server
kubectl -n argocd rollout status deployment argocd-server --timeout=300s

create_or_update_minio_credentials_secret
kubectl apply -f "${gitops_dir}/bootstrap/root-application.yaml"

bash "${repo_root}/slurm/install-dummy-slurm-cluster.sh"

wait_for_service argocd argocd-server
wait_for_service argo argo-server
wait_for_service argo minio
wait_for_service argo minio-console
wait_for_service kubeflow katib-ui

resolved_argocd_nodeport="$(get_nodeport argocd argocd-server 443)"
resolved_argo_workflows_nodeport="$(get_nodeport argo argo-server 2746)"
resolved_minio_api_nodeport="$(get_nodeport argo minio 9000)"
resolved_minio_console_nodeport="$(get_nodeport argo minio-console 9001)"
resolved_katib_nodeport="$(get_nodeport kubeflow katib-ui 80)"

restart_workload_if_present argo statefulset minio
wait_for_service argo minio
wait_for_service argo minio-console

upload_example_datasets "$(minikube ip)" "${resolved_minio_api_nodeport}"

if [[ "${start_nodeport_relays}" == "true" ]]; then
  nohup env \
    ARGOCD_NODEPORT="${resolved_argocd_nodeport}" \
    ARGO_WORKFLOWS_NODEPORT="${resolved_argo_workflows_nodeport}" \
    MINIO_API_NODEPORT="${resolved_minio_api_nodeport}" \
    MINIO_CONSOLE_NODEPORT="${resolved_minio_console_nodeport}" \
    KATIB_NODEPORT="${resolved_katib_nodeport}" \
    bash "${repo_root}/scripts/relay-nodeports.sh" "$(minikube ip)" >"${relay_log}" 2>&1 &
  relay_pid=$!
  sleep 3
  if ! kill -0 "${relay_pid}" >/dev/null 2>&1; then
    echo "Failed to start NodePort relays. Log output:" >&2
    cat "${relay_log}" >&2
    exit 1
  fi
fi

mkdir -p "${ssh_dir}"
chmod 700 "${ssh_dir}"

if [ ! -f "${ssh_key_path}" ]; then
  ssh-keygen -q -t ed25519 -a 100 -N "" -f "${ssh_key_path}" -C "slurm-access"
else
  echo "SSH key already exists at ${ssh_key_path}; skipping generation."
fi

public_key="$(cat "${ssh_key_path}.pub")"
docker exec "${slurm_container_name}" /bin/sh -lc "umask 077
mkdir -p /root/.ssh
touch /root/.ssh/authorized_keys
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys
grep -qxF '${public_key}' /root/.ssh/authorized_keys || printf '%s\n' '${public_key}' >> /root/.ssh/authorized_keys
echo 'Added public key to /root/.ssh/authorized_keys'"

kubectl -n argo create secret generic slurm-ssh-key \
  --from-file=ssh-privatekey=${ssh_key_path} \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl -n argo apply -f "${repo_root}/secret-templates/ssh-creds-example.yaml"

if [[ "${start_nodeport_relays}" == "true" ]]; then
  browser_host="127.0.0.1"
else
  browser_host="$(minikube ip)"
fi

if [[ -n "${CODESPACES:-}" ]]; then
  echo "Running in GitHub Codespaces. Open these services from the PORTS tab using the forwarded port URLs."
elif [[ "${start_nodeport_relays}" == "true" ]]; then
  echo "Running in a devcontainer. Open these services from your local browser using the relayed localhost ports below."
else
  echo "Running on the local host. Open these services using the Minikube IP and NodePorts below."
fi

echo "ArgoCD Server: https://${browser_host}:${resolved_argocd_nodeport}"
echo "ArgoCD Username: admin"
echo "ArgoCD Password: ${argocd_password}"
echo "Argo Workflows Server: https://${browser_host}:${resolved_argo_workflows_nodeport}"
echo "MinIO Console: https://${browser_host}:${resolved_minio_console_nodeport}"
echo "MinIO Username: ${minio_access_key}"
echo "MinIO Password: ${minio_secret_key}"
echo "Datasets uploaded to MinIO bucket: ${minio_bucket}"
echo "Katib Frontend: https://${browser_host}:${resolved_katib_nodeport}/katib/"
echo "Setup complete."
if [[ "${start_nodeport_relays}" == "true" ]]; then
  echo "Relay log (if needed): ${relay_log}"
fi
echo "Credentials file: ${credentials_file}"
echo "SSH private key: ${ssh_key_path}"
